### ISSUE TITLE
[Topic Suggestion] Technical Writing for Non-Native English Speakers

### ISSUE THREAD

**Issue by ahasall** [wesleygrimes/technical-writers-summit#1]
Let me jot down some ideas:

1. How to write great technical content when you are a non-native English speakers
* writing with confidence
* thinking in English
* finding inspiration

2. Writing technical content for people whose English isn’t the first language
* tips and tricks to make your content more

**Comment by wesleygrimes** [comment]
Are you willing to take the lead on this topic? Maybe plan out a short summary?

**Comment by ahasall** [comment]
I can take the lead on this topic. I also added a short description of the topic.

**Comment by wesleygrimes** [comment]
@ahasall This topic made the cut! Can you start preparing and submit an outline?

**Comment by ahasall** [comment]
Yes. I will work on it.

**Comment by ahasall** [comment]
Here are the slides: http://bit.ly/2H4xfPv

**Comment by wesleygrimes** [comment]
Great job!
