### ISSUE TITLE
[Topic Suggestion] Where to publish? 

### ISSUE THREAD

**Issue by bniedermeyer** [wesleygrimes/technical-writers-summit#2]
There's so many options for where and how you can share your work. Medium? Dev.to? Self hosted blog? Some of these have different options (paywalls etc...) that can encourage or discourage people from reading your work. What are good strategies to making sure people can see what you write?

**Comment by wesleygrimes** [comment]
Would you take the lead on this topic? You don't have to have all the answers, just want someone to facilitate it.

**Comment by bniedermeyer** [comment]
Sure

**Comment by wesleygrimes** [comment]
@bniedermeyer  OK this has made the cut! Instead of diving too deep into a specific avenue, I think it would be good if you could do a pros and cons or survey of all the available places and avenues folks can publish to.

Do you think you could have an outline ready soon?

**Comment by wesleygrimes** [comment]
@bniedermeyer OK this has made the cut! Instead of diving too deep into a specific avenue, I think it would be good if you could do a pros and cons or survey of all the available places and avenues folks can publish to.

Do you think you could have an outline ready soon?

**Comment by bniedermeyer** [comment]
@wesleygrimes sure - what all are you looking for? More of a presentation or conversation starter?

**Comment by wesleygrimes** [comment]
A presentation would be nice. Nothing fancy at all. Just some talking points so you can guide the discussion. I’m sure myself and some of the other experienced writers will jump in and add to the discussion as well. Very casual atmosphere. 

-Wes

**Comment by wesleygrimes** [comment]
https://github.com/bniedermeyer/publishing-tech-writing-ng-conf/blob/master/publishing-tech-writing.pdf

Great job Brenden!
