### ISSUE TITLE
[Topic Suggestion] Technical writing workflows

### ISSUE THREAD

**Issue by bniedermeyer** [wesleygrimes/technical-writers-summit#3]
What’s your process for writing a technical article? Do you build the example first or wait until the end? Do you use a headless cms or commit a .md file of the article in another branch? What’s your process for planning content and knowing what to write about?

**Comment by wesleygrimes** [comment]
I will take this topic and explore it as part of my opening statements.

**Comment by wesleygrimes** [comment]
https://docs.google.com/presentation/d/1gbvPZuM-zPz37vV_Zx3FM0sEQHNBowPCER0s4NK5Vh4
