### ISSUE TITLE
[Topic Suggestion] JAMstack on Netlify

### ISSUE THREAD

**Issue by pjlamb12** [wesleygrimes/technical-writers-summit#4]
We could cover the simplicity of using GitHub + Netlify to deploy a JAMstack app for your site + blog.

Included in this, we could talk about using Netlify as a custom link shortener as well.

**Comment by wesleygrimes** [comment]
Great idea! I did something similar, and for .99 (cost of domain name),  I was able to publish a personal website using netlify. My site is built on jekyll, but I know lots of folks are using Gatsby.js, either way we could leave out these details and just discuss the FLOW of the process.

**Comment by pjlamb12** [comment]
Yeah, Netlify is great and I think will help people see that they don't need a lot of server management knowledge to get a site deployed.

**Comment by wesleygrimes** [comment]
https://pjlc.dev/ngconf-writers

Great Job Preston!
