### ISSUE TITLE
[Topic Suggestion] Grammar, syntax, code highlighting, acronym standardization

### ISSUE THREAD

**Issue by seangwright** [wesleygrimes/technical-writers-summit#8]
Writers in other technical fields have standard guidelines for grammar, syntax, code highlighting, acronym, formatting, ect...

[MLA](https://owl.purdue.edu/owl/research_and_citation/mla_style/mla_formatting_and_style_guide/mla_formatting_and_style_guide.html)
[APA](https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/general_format.html)
[Mathematical Notation](https://en.wikipedia.org/wiki/Mathematical_notation)

Often I don't know what direction I should go when writing.
- Oxford commas
- `<code></code>` or `<pre></pre>`
- When / how to use [Medium](https://blog.medium.com/tips-and-tricks-for-medium-writers-1d79498101c3)'s features
- Citations/links
- Acronyms (what can be assumed for your audience)
- Emojis (I like them, but do we use them too much?)
- [Consistent voice](https://www.dummies.com/education/language-arts/grammar/improve-your-writing-by-using-a-consistent-voice/)
- [Consistent tense](https://www.grammarly.com/blog/verb-tense-consistency/)

Some of these apply to writing in general but because of the highly technical nature of Software / IT blogging and writing it can be tricky to know how and when to apply these rules.

Does anyone know resources, standards, or best practices that have served you well?

**Comment by seangwright** [comment]
I'll facilitate this topic.

If anyone wants to touch on something specific, comment here and I will make sure to include it with some background information.

**Comment by wesleygrimes** [comment]
@seangwright  OK This topic made the cut! Looking forward to it.

**Comment by seangwright** [comment]
A link to my slides

https://docs.google.com/presentation/d/1aMxhIi_ep3-2PqwEy5RlqkT2r3iiaZx7EkA_qon5QKg/edit?usp=sharing

**Comment by wesleygrimes** [comment]
Great job Sean!
